api:
  type:     rest
  resource: ../src/Controller/
  prefix:   api

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmi_api_doc.controller.swagger_ui }

api_auth_login:
  path: /api/auth/login
  methods:  [POST]

gesdinet_jwt_refresh_token:
  path:       /api/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh